import { Apartment, emptyApartment } from "./types";

function slug(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function make(partial: Partial<Apartment>): Apartment {
  return {
    ...emptyApartment(),
    id: partial.name ? slug(partial.name) : "",
    updatedAt: new Date().toISOString(),
    ...partial,
  };
}

const today = "2026-05-26";

export const SEED_APARTMENTS: Apartment[] = [
  make({
    rank: 1,
    status: "Strong contender",
    name: "4th West Apartments",
    address: "255 N 400 West, Salt Lake City, UT 84103",
    neighborhood: "Downtown Hardware District",
    website: "https://4thwest.com/",
    rent: 2447,
    rentRangeLow: 2447,
    rentRangeHigh: 4151,
    unitType: "2BR/2BA",
    squareFeet: 1038,
    availability:
      "36 units available (May 2026); multiple 2BR floor plans (Bonneville 1,038 sqft, Olympus 1,107 sqft, Red River 1,320 sqft).",
    leaseTerms:
      "12-month standard. Specials: up to 8 weeks free + $3,000 Modern Message gift card on select units; 8 weeks free on ready-now homes; $500 Lee's Market gift card for Look & Lease.",
    fees: {
      application: 50,
      admin: null,
      deposit: 300,
      parking: null,
      petDeposit: 100,
      petFee: 300,
      petRent: 45,
      other: ["3x rent income requirement"],
    },
    utilities: {
      included: [],
      tenantPaid: ["resident-managed per lease"],
      estimatedMonthly: 150,
    },
    parking: {
      available: true,
      covered: true,
      cost: null,
      notes: "On-site parking; cost not disclosed publicly — confirm at tour.",
    },
    petPolicy: {
      allowed: true,
      speciesAllowed: "dogs + cats",
      maxPets: 2,
      weightLimit: null,
      breedRestrictions: "Standard restrictions; call leasing for specifics",
      petAmenities: ["bark park", "dog grooming area / dog wash"],
      notes:
        "$100 pet deposit + $300 pet fee + $45/mo pet rent (per RentCafe).",
    },
    amenities: [
      "pool",
      "hot tub",
      "sauna",
      "fitness center",
      "concierge",
      "basketball court",
      "bark park",
      "dog grooming",
      "BBQ grills",
      "10-foot ceilings",
      "chef-inspired kitchens",
      "city + mountain views",
      "walk-in closets",
      "in-unit W/D",
      "balconies",
      "stainless appliances",
    ],
    locationNotes:
      "Downtown Hardware District; close to TRAX, Trolley Square, Liberty Park; walking distance to downtown core.",
    pros: [
      "Best dog-focused downtown match (bark park + grooming)",
      "Strong amenity stack with pool, sauna, basketball",
      "287 reviews / 4.2 average; maintenance and staff highly rated",
      "Multiple 2BR layouts available with 8 weeks free special",
    ],
    cons: [
      "Top-tier 2BR pricing can exceed $2,400 cap without specials",
      "Some noise complaints (3.9 noise rating)",
      "Parking cost not disclosed publicly",
    ],
    redFlags: ["Safety rating 4.0 — area-specific, verify on tour"],
    unknowns: ["Exact pet weight cap", "Parking monthly cost"],
    dealbreakers: [],
    niceToHaves: ["Dog grooming on site", "Pool + sauna"],
    followUpQuestions: [
      "What 2BR units stay under $2,400 all-in after applying current specials?",
      "Is there a specific dog weight limit, and what breeds are restricted?",
      "What's the monthly parking cost?",
      "What utilities does the resident pay vs. building?",
    ],
    comments: [],
    sources: [
      {
        id: "4w-1",
        url: "https://4thwest.com/",
        type: "official",
        dateAccessed: today,
        notes: "Address, unit types, current specials",
        confidence: "high",
      },
      {
        id: "4w-2",
        url: "https://www.rentcafe.com/apartments/ut/salt-lake-city/4th-west/default.aspx",
        type: "listing",
        dateAccessed: today,
        notes: "Pet fees, rent ranges, app + deposit",
        confidence: "high",
      },
      {
        id: "4w-3",
        url: "https://www.apartmentratings.com/ut/salt-lake-city/4th-west-apartments_9199332346275163722/",
        type: "review",
        dateAccessed: today,
        notes: "4.2/5 across 287 reviews",
        confidence: "high",
      },
    ],
    scores: {
      value: 6,
      location: 9,
      unitQuality: 8,
      amenities: 9,
      commute: 9,
      fees: 6,
      risk: 7,
      personalPreference: 8,
    },
    tour: {
      scheduled: false,
      date: "",
      completed: false,
      notes: "",
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      applicationDeadline: "",
      requiredDocuments: "",
    },
    reviewSummary: {
      rating: 4.2,
      reviewCount: 287,
      source: "ApartmentRatings.com",
      commonPraise: [
        "responsive maintenance (4.6)",
        "friendly staff (4.7)",
        "good neighborhood",
        "modern finishes",
        "great views",
      ],
      commonComplaints: ["noise (3.9)", "safety concerns (4.0)"],
    },
    tags: ["dog-friendly", "downtown", "luxury", "pool"],
    confidence: "high",
    missingData: [
      "exact dog weight limit",
      "restricted breed list",
      "parking monthly cost",
      "utility estimate",
    ],
  }),

  make({
    rank: 2,
    status: "Strong contender",
    name: "The Morton",
    address: "245 S 200 East, Salt Lake City, UT 84111",
    neighborhood: "Downtown Salt Lake City",
    website: "https://www.liveatthemorton.com/",
    rent: 2098,
    rentRangeLow: 2098,
    rentRangeHigh: 5101,
    unitType: "2BR/2BA",
    squareFeet: 910,
    availability:
      "2BR Benson + Sorento (910 sqft) actively listed; pricing $2,098–$5,101 depending on unit/term.",
    leaseTerms:
      "Up to 8 weeks free base rent on select homes; min lease applies. Greystar-managed.",
    fees: {
      application: 45,
      admin: null,
      deposit: 500,
      parking: 125,
      petDeposit: 250,
      petFee: 250,
      petRent: null,
      other: ["3x rent income", "Greystar pet screening may apply"],
    },
    utilities: {
      included: [],
      tenantPaid: ["all utilities resident-paid"],
      estimatedMonthly: 150,
    },
    parking: {
      available: true,
      covered: true,
      cost: 125,
      notes:
        "Controlled-access garage. Reviews note occasional broken garage door.",
    },
    petPolicy: {
      allowed: true,
      speciesAllowed: "dogs + cats",
      maxPets: 2,
      weightLimit: null,
      breedRestrictions: "Greystar standard; verify with leasing",
      petAmenities: ["pet terrace", "dog wash / grooming area"],
      notes: "$250 deposit + $250 fee per Apartments.com.",
    },
    amenities: [
      "24-hour fitness center",
      "rooftop terrace",
      "pet terrace",
      "dog wash",
      "controlled-access parking",
      "package lockers",
      "bike storage",
      "smoke-free",
      "in-unit W/D",
      "stainless appliances",
      "quartz countertops",
      "smart home tech",
      "9–10 ft ceilings",
      "walk-in closets",
    ],
    locationNotes:
      "Heart of downtown SLC. Walk Score 95 (Walker's Paradise), Transit Score 70. Close to TRAX, downtown employers, dining.",
    pros: [
      "Walk Score 95 — heart of downtown",
      "Dog wash + pet terrace",
      "8 weeks free promo on select units",
      "Confirmed $125/mo covered parking + $500 deposit",
    ],
    cons: [
      "Reviews flag spotty Amazon package delivery + broken garage door",
      "Noise reports from urban core",
      "Per-unit pricing varies widely ($2,098–$5,101)",
    ],
    redFlags: ["Common-area cleanliness complaints", "Garage door reliability"],
    unknowns: ["Specific dog weight + breed limits", "Monthly pet rent"],
    dealbreakers: [],
    niceToHaves: ["Rooftop terrace", "Bike storage"],
    followUpQuestions: [
      "Confirm monthly pet rent vs. one-time fees",
      "Is the garage door issue still ongoing in May 2026?",
      "What 2BR floor plans hit close to $2,098 with the 8-weeks-free promo?",
    ],
    comments: [],
    sources: [
      {
        id: "mt-1",
        url: "https://www.rentcafe.com/apartments/ut/salt-lake-city/the-morton-1/default.aspx",
        type: "listing",
        dateAccessed: today,
        notes: "Rent ranges, parking $125, deposit $500, pet fees",
        confidence: "high",
      },
      {
        id: "mt-2",
        url: "https://hotpads.com/the-morton-salt-lake-city-ut-84111-w53m2c/pad",
        type: "listing",
        dateAccessed: today,
        notes: "Confirmed $125/mo parking",
        confidence: "high",
      },
      {
        id: "mt-3",
        url: "https://www.yelp.com/biz/the-morton-salt-lake-city-4",
        type: "review",
        dateAccessed: today,
        notes: "11 reviews, mixed feedback",
        confidence: "medium",
      },
    ],
    scores: {
      value: 7,
      location: 10,
      unitQuality: 8,
      amenities: 8,
      commute: 10,
      fees: 7,
      risk: 6,
      personalPreference: 8,
    },
    tour: {
      scheduled: false,
      date: "",
      completed: false,
      notes: "",
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      applicationDeadline: "",
      requiredDocuments: "",
    },
    reviewSummary: {
      rating: 5.0,
      reviewCount: 11,
      source: "Yelp",
      commonPraise: [
        "attentive management",
        "rooftop + gym amenities",
        "community feel",
        "pet-friendly amenities",
        "great location",
      ],
      commonComplaints: [
        "spotty Amazon delivery",
        "broken garage doors",
        "common-area cleanliness",
        "maintenance communication",
        "noise",
      ],
    },
    tags: ["dog-friendly", "downtown", "rooftop", "central"],
    confidence: "high",
    missingData: ["pet weight limit", "monthly pet rent", "admin fee"],
  }),

  make({
    rank: 3,
    status: "Strong contender",
    name: "Crossing at 9th",
    address: "880 W 200 S, Salt Lake City, UT 84104",
    neighborhood: "Granary District / Poplar Grove edge",
    website: "https://www.crossingat9th.com/",
    rent: 1825,
    rentRangeLow: 1825,
    rentRangeHigh: 2265,
    unitType: "2BR/2BA",
    squareFeet: 880,
    availability:
      "2BR availability $1,825–$2,265 across 7+ floor plans (verify current specials with leasing office).",
    leaseTerms: "Standard terms; check leasing office for active promos.",
    fees: {
      application: null,
      admin: null,
      deposit: null,
      parking: null,
      petDeposit: null,
      petFee: 300,
      petRent: 45,
      other: ["Payments via Bilt Rewards"],
    },
    utilities: {
      included: [],
      tenantPaid: ["electricity", "water", "gas", "internet", "trash"],
      estimatedMonthly: 150,
    },
    parking: {
      available: true,
      covered: true,
      cost: null,
      notes: "Secure underground + covered parking with controlled access",
    },
    petPolicy: {
      allowed: true,
      speciesAllowed: "dogs + cats",
      maxPets: 2,
      weightLimit: null,
      breedRestrictions: "Apply; specifics not published",
      petAmenities: ["dog park on site", "pet wash"],
      notes: "$300 fee + $45/mo per Apartments.com",
    },
    amenities: [
      "pool with sundeck",
      "fitness center",
      "resident clubroom",
      "co-working space",
      "rooftop lounge",
      "outdoor fire pit",
      "courtyards",
      "secure bike storage",
      "pet wash",
      "dog park",
      "secure underground parking",
      "smart locks",
      "in-unit W/D",
      "stainless appliances",
      "quartz countertops",
      "USB-C outlets",
    ],
    locationNotes:
      "Built 2025 (new construction); 205 units in 4 stories. Granary District; walk to Red Iguana, Copper Onion, City Creek, Trolley Square. Downtown-adjacent.",
    pros: [
      "New construction (2025) with modern finishes throughout",
      "Dog park + pet wash on site — strongest dog setup at this price",
      "Rooftop lounge + pool",
    ],
    cons: [
      "Granary District location less polished than central downtown",
      "Limited resident feedback so far (new building)",
      "Bilt Rewards payment platform adds friction for some renters",
    ],
    redFlags: [],
    unknowns: [
      "Application + admin fee",
      "Security deposit policy",
      "Pet weight limit",
      "Parking cost",
    ],
    dealbreakers: [],
    niceToHaves: ["Smart locks", "Co-working space"],
    followUpQuestions: [
      "Are any concession specials active right now?",
      "What is the application fee + security deposit policy?",
      "What's parking pricing? Is it included for 2BRs?",
      "Has the dog park been well-maintained since opening?",
    ],
    comments: [],
    sources: [
      {
        id: "c9-1",
        url: "https://www.crossingat9th.com/",
        type: "official",
        dateAccessed: today,
        notes: "Starting prices, Bilt payments, amenities",
        confidence: "high",
      },
      {
        id: "c9-2",
        url: "https://www.crossingat9th.com/floor-plans",
        type: "official",
        dateAccessed: today,
        notes: "Full floor plan list with sqft + ranges",
        confidence: "high",
      },
      {
        id: "c9-3",
        url: "https://www.apartments.com/crossing-at-9th-salt-lake-city-ut/5x137tq/",
        type: "listing",
        dateAccessed: today,
        notes: "205 units / 4 stories / built 2025; 12 weeks free; pet fees",
        confidence: "high",
      },
    ],
    scores: {
      value: 9,
      location: 7,
      unitQuality: 9,
      amenities: 9,
      commute: 7,
      fees: 8,
      risk: 6,
      personalPreference: 8,
    },
    tour: {
      scheduled: false,
      date: "",
      completed: false,
      notes: "",
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      applicationDeadline: "",
      requiredDocuments: "",
    },
    reviewSummary: {
      rating: 3.2,
      reviewCount: null,
      source: "ApartmentHomeLiving.com",
      commonPraise: [
        "modern finishes",
        "rooftop with city views",
        "new construction quality",
        "dog park + pet amenities",
      ],
      commonComplaints: ["limited feedback yet (newly opened)"],
    },
    tags: ["dog-park", "value", "new-2025", "pool"],
    confidence: "medium",
    missingData: [
      "app + admin fees",
      "specific deposit",
      "pet weight + breed list",
      "parking cost",
      "comprehensive review data",
    ],
  }),

  make({
    rank: 4,
    status: "Strong contender",
    name: "Gateway 505",
    address: "505 W 100 South, Salt Lake City, UT 84101",
    neighborhood: "Downtown / Gateway District",
    website: "https://www.gateway505.com/",
    rent: 1869,
    rentRangeLow: 1869,
    rentRangeHigh: 2040,
    unitType: "2BR/2BA",
    squareFeet: 996,
    availability:
      "Limited 2BR units 996–1,344 sqft $1,869–$2,040 (re-check ApartmentList for current count).",
    leaseTerms:
      "12-month standard; current promo 'Up to 8 Weeks Free on Your New Home' (base rent, restrictions apply).",
    fees: {
      application: 45,
      admin: null,
      deposit: 500,
      parking: null,
      petDeposit: null,
      petFee: 350,
      petRent: 75,
      other: ["3x rent income"],
    },
    utilities: {
      included: [],
      tenantPaid: ["all utilities resident-paid"],
      estimatedMonthly: 150,
    },
    parking: {
      available: false,
      covered: false,
      cost: null,
      notes:
        "MAJOR: building FAQ explicitly states NO on-site parking. Residents must find off-site parking.",
    },
    petPolicy: {
      allowed: true,
      speciesAllowed: "dogs + cats",
      maxPets: 2,
      weightLimit: 70,
      breedRestrictions:
        "Aggressive breeds prohibited (Rottweiler, Doberman, Pit Bull, others)",
      petAmenities: ["pet spa"],
      notes: "70 lb weight cap (some listings show 75); breed list applies.",
    },
    amenities: [
      "heated pool",
      "spa/hot tub",
      "two-story fitness center",
      "rooftop deck",
      "wine room",
      "clubhouse + game room",
      "business center with coffee bar",
      "bike/ski/snowboard repair shop",
      "pet spa",
      "24-hour maintenance",
      "in-unit W/D",
      "stainless appliances",
      "walk-in closets",
      "private balconies",
    ],
    locationNotes:
      "Adjacent to The Gateway mall; walk to shops, restaurants, Delta Center, TRAX. NO parking on site is a significant downside for car owners.",
    pros: [
      "Best 2BR/2BA value in downtown ($1,869–$2,040)",
      "Up to 8 weeks free promo",
      "Strong amenity stack: pool, spa, two-story gym, rooftop",
      "Pet spa + dog-friendly",
    ],
    cons: [
      "NO on-site parking — must find off-site",
      "Garage door + trash service complaints recurring in reviews",
      "Reddit/review reports cite homelessness concerns near building",
    ],
    redFlags: [
      "No on-site parking (FAQ-confirmed)",
      "Insufficient security camera coverage per reviews",
      "Pet waste enforcement issues per reviews",
    ],
    unknowns: ["Admin fee", "Exact pet deposit vs fee", "Utility estimates"],
    dealbreakers: [],
    niceToHaves: ["Wine room + storage", "Ski/snowboard repair shop"],
    followUpQuestions: [
      "Where do current residents park? What's nearby monthly cost?",
      "Status of security camera + safety patrol upgrades?",
      "Confirm pet weight (70 vs 75 lb) + restricted breed list",
    ],
    comments: [],
    sources: [
      {
        id: "g5-1",
        url: "https://www.gateway505.com/",
        type: "official",
        dateAccessed: today,
        notes:
          "Confirmed rent ranges, $45 app, $500 deposit, $75/mo pet rent, 70lb weight limit",
        confidence: "high",
      },
      {
        id: "g5-2",
        url: "https://www.apartmentlist.com/ut/salt-lake-city/gateway-505",
        type: "listing",
        dateAccessed: today,
        notes: "confirms NO parking; inventory count fluctuates",
        confidence: "high",
      },
      {
        id: "g5-3",
        url: "https://birdeye.com/gateway-505-159915537363091",
        type: "review",
        dateAccessed: today,
        notes: "3.9 stars, 344 reviews",
        confidence: "high",
      },
    ],
    scores: {
      value: 9,
      location: 7,
      unitQuality: 8,
      amenities: 8,
      commute: 8,
      fees: 8,
      risk: 4,
      personalPreference: 7,
    },
    tour: {
      scheduled: false,
      date: "",
      completed: false,
      notes: "",
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      applicationDeadline: "",
      requiredDocuments: "",
    },
    reviewSummary: {
      rating: 3.9,
      reviewCount: 344,
      source: "Birdeye",
      commonPraise: [
        "friendly + helpful staff",
        "great gym and pool",
        "prime downtown location",
        "safety patrol responsiveness",
      ],
      commonComplaints: [
        "garage door frequently broken",
        "trash service issues",
        "pet waste enforcement",
        "no parking offered",
      ],
    },
    tags: ["value", "downtown", "dog-friendly", "no-parking"],
    confidence: "high",
    missingData: ["admin fee", "pet deposit vs fee breakdown"],
  }),

  make({
    rank: 5,
    status: "Interested",
    name: "Karve on Broadway",
    address: "325 E 300 South, Salt Lake City, UT 84111",
    neighborhood: "Central City / Broadway District",
    website: "https://www.karveonbroadway.com/",
    rent: 2120,
    rentRangeLow: 2120,
    rentRangeHigh: 3395,
    unitType: "2BR/2BA",
    squareFeet: 1042,
    availability:
      "~14 units available (May 2026); 2BR units 1,042–1,263 sqft listed $2,120–$3,320.",
    leaseTerms:
      "Current: 'Now Offering 10 Weeks Free on Immediate Move-Ins' (restrictions by floor plan).",
    fees: {
      application: null,
      admin: null,
      deposit: null,
      parking: null,
      petDeposit: null,
      petFee: null,
      petRent: null,
      other: [
        "Pet deposit per pet + one-time pet fee per unit (amounts not published)",
        "3x rent income",
      ],
    },
    utilities: {
      included: [],
      tenantPaid: ["utilities not specified as included"],
      estimatedMonthly: 150,
    },
    parking: {
      available: true,
      covered: true,
      cost: null,
      notes:
        "Access-controlled garage. ApartmentList lists garage parking as included amenity.",
    },
    petPolicy: {
      allowed: true,
      speciesAllowed: "dogs + cats",
      maxPets: null,
      weightLimit: null,
      breedRestrictions: "Breed restrictions; call leasing",
      petAmenities: ["dog wash station"],
      notes: "Pet fees not published online",
    },
    amenities: [
      "two-story fitness center",
      "resort-style rooftop pool with jumbotron",
      "co-working lounge",
      "dog wash station",
      "EV charging",
      "package lockers",
      "access-controlled garage",
      "business center",
      "in-unit W/D",
      "hardwood-style flooring",
      "quartz countertops",
    ],
    locationNotes:
      "Walk Score 93 (Walker's Paradise), Transit Score 68. Walkable to downtown, Library Square, Broadway dining/nightlife.",
    pros: [
      "Walk Score 93 + central Broadway location",
      "Rooftop pool with jumbotron",
      "Dog wash on site",
      "10 weeks free promo on immediate move-ins",
    ],
    cons: [
      "Pet fees not publicly disclosed — could be high",
      "Reviews note elevator maintenance + garage security concerns",
      "Higher base 2BR start ($2,120) than Crossing/Gateway",
    ],
    redFlags: [
      "Security concerns in parking garage per reviews",
      "Frequent elevator maintenance issues per reviews",
    ],
    unknowns: ["App fee", "Deposit", "All pet fees", "Pet weight limit"],
    dealbreakers: [],
    niceToHaves: ["Rooftop jumbotron"],
    followUpQuestions: [
      "What are the actual pet deposit + fee + monthly rent figures?",
      "Has elevator maintenance improved recently?",
      "Are garage security upgrades planned?",
      "Confirm parking is included for 2BR leases",
    ],
    comments: [],
    sources: [
      {
        id: "kv-1",
        url: "https://www.karveonbroadway.com/",
        type: "official",
        dateAccessed: today,
        notes: "Address, units, amenities, 10 weeks free promo",
        confidence: "high",
      },
      {
        id: "kv-2",
        url: "https://www.apartmentlist.com/ut/salt-lake-city/karve-on-broadway",
        type: "listing",
        dateAccessed: today,
        notes: "Walk 93/Transit 68, garage parking included",
        confidence: "high",
      },
    ],
    scores: {
      value: 7,
      location: 9,
      unitQuality: 8,
      amenities: 8,
      commute: 9,
      fees: 6,
      risk: 5,
      personalPreference: 7,
    },
    tour: {
      scheduled: false,
      date: "",
      completed: false,
      notes: "",
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      applicationDeadline: "",
      requiredDocuments: "",
    },
    reviewSummary: {
      rating: null,
      reviewCount: null,
      source: "ApartmentList (collecting verified resident reviews)",
      commonPraise: [
        "spacious modern apartments",
        "rooftop pool/hot tub",
        "newer building",
        "convenient location near TRAX",
        "friendly leasing agents",
      ],
      commonComplaints: [
        "frequent elevator maintenance",
        "trash chutes locked",
        "security in parking garage",
        "noise from other residents",
      ],
    },
    tags: ["central", "downtown", "rooftop", "modern"],
    confidence: "medium",
    missingData: [
      "app + admin fees",
      "deposit",
      "all pet fees",
      "max pets",
      "weight limit",
      "breed list",
    ],
  }),

  make({
    rank: 6,
    status: "Interested",
    name: "The Citizen",
    address: "515 S 400 E, Salt Lake City, UT 84111",
    neighborhood: "Central City / Liberty Wells edge",
    website: "https://thecitizenslc.com/",
    rent: 2325,
    rentRangeLow: 2325,
    rentRangeHigh: 3000,
    unitType: "2BR/2BA",
    squareFeet: 832,
    availability:
      "Multiple 2BR floor plans available: 2 Bed B ~$2,400, 2 Bed F ~$3,000, Townhome T-2C ~$3,499. Some plans sold out.",
    leaseTerms:
      "6–18 month leases. Special: up to 12 weeks free (official site); 8 weeks free + $125 off/mo for 12 months (Apartments.com).",
    fees: {
      application: null,
      admin: null,
      deposit: null,
      parking: 100,
      petDeposit: 200,
      petFee: 300,
      petRent: 50,
      other: [],
    },
    utilities: {
      included: [],
      tenantPaid: ["electricity", "water", "gas", "internet", "trash"],
      estimatedMonthly: 175,
    },
    parking: {
      available: true,
      covered: true,
      cost: 100,
      notes: "Parking garage; RV charging on site",
    },
    petPolicy: {
      allowed: true,
      speciesAllowed: "dogs + cats",
      maxPets: 2,
      weightLimit: null,
      breedRestrictions: "Standard; contact leasing",
      petAmenities: [
        "dog wash",
        "near Liberty Park (0.8 mi)",
        "Pioneer Dog Park (1.6 mi)",
        "Herman Franks Dog Park (1.7 mi)",
      ],
      notes:
        "$200 refundable deposit + $300 one-time fee + $50/mo pet rent per pet (official guide).",
    },
    amenities: [
      "resort-style pool",
      "hot tub",
      "poolside cabanas + fire pit",
      "rooftop lounge with 360° views",
      "fitness center",
      "clubroom with fireplace",
      "courtyard with zen fountain",
      "BBQ grills",
      "on-site market",
      "dog wash",
      "bike storage + repair",
      "RV charging",
      "in-unit W/D",
      "hardwood floors",
      "quartz countertops",
    ],
    locationNotes:
      "Downtown east edge; walkable to Trolley Square, Liberty Park, downtown core. Built 2024.",
    pros: [
      "Brand new (2024) with luxury finishes",
      "Up to 12 weeks free brings 2BR effective rate close to $2,400",
      "Dog wash + 3 nearby off-leash parks within 2 mi",
      "On-site market is rare amenity",
    ],
    cons: [
      "Base 2BR pricing is higher than Gateway/Crossing",
      "Limited resident reviews so far (new 2024 building)",
      "Utilities resident-paid; estimate ~$175/mo on top",
    ],
    redFlags: [
      "Cleanliness in common areas + maintenance gaps noted in limited reviews",
    ],
    unknowns: ["App + admin fees", "Security deposit", "Pet weight limit"],
    dealbreakers: [],
    niceToHaves: ["On-site market", "RV charging"],
    followUpQuestions: [
      "Effective 2BR rate after applying 12 weeks free?",
      "What is the application fee + security deposit?",
      "Has cleanliness/maintenance improved recently?",
    ],
    comments: [],
    sources: [
      {
        id: "ct-1",
        url: "https://thecitizenslc.com/",
        type: "official",
        dateAccessed: today,
        notes: "Address, units, 12 weeks free promo",
        confidence: "high",
      },
      {
        id: "ct-2",
        url: "https://thecitizenslc.com/guide-to-pet-friendly-apartments-salt-lake-city-utah/",
        type: "official",
        dateAccessed: today,
        notes: "Pet fees: $200 deposit, $300 fee, $50/mo",
        confidence: "high",
      },
      {
        id: "ct-3",
        url: "https://www.apartments.com/the-citizen-salt-lake-city-ut/rdvrp63/",
        type: "listing",
        dateAccessed: today,
        notes: "Parking $100/mo, 8 weeks free + $125 off promo",
        confidence: "high",
      },
    ],
    scores: {
      value: 6,
      location: 8,
      unitQuality: 9,
      amenities: 9,
      commute: 8,
      fees: 6,
      risk: 6,
      personalPreference: 7,
    },
    tour: {
      scheduled: false,
      date: "",
      completed: false,
      notes: "",
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      applicationDeadline: "",
      requiredDocuments: "",
    },
    reviewSummary: {
      rating: null,
      reviewCount: null,
      source: "Limited (new 2024 building)",
      commonPraise: [
        "modern design + finishes",
        "top-notch amenities",
        "welcoming staff",
        "downtown location",
      ],
      commonComplaints: ["common-area cleanliness", "maintenance gaps"],
    },
    tags: ["luxury", "new-2024", "dog-wash", "pool"],
    confidence: "medium",
    missingData: [
      "application fee",
      "admin fee",
      "security deposit",
      "pet weight limit",
      "specific breed restrictions",
    ],
  }),

  make({
    rank: 7,
    status: "Interested",
    name: "Altitude on Fifth",
    address: "135 S 500 W, Salt Lake City, UT 84101",
    neighborhood: "Downtown West / Granary District",
    website: "https://www.altitudeonfifthapartments.com/",
    rent: 1499,
    rentRangeLow: 1499,
    rentRangeHigh: 3525,
    unitType: "2BR/2BA",
    squareFeet: 873,
    availability:
      "5+ units listed; multiple 2BR floor plans actively available with promo pricing.",
    leaseTerms: "Standard 12-month; 8 weeks FREE on select 2BR plans.",
    fees: {
      application: 35,
      admin: null,
      deposit: 400,
      parking: null,
      petDeposit: null,
      petFee: null,
      petRent: null,
      other: [
        "$0 deposit option on approved credit (~$8.25/mo fee instead)",
        "PetScreening third-party application (fee per pet)",
      ],
    },
    utilities: {
      included: [],
      tenantPaid: ["electricity", "water", "gas", "internet", "trash"],
      estimatedMonthly: 150,
    },
    parking: {
      available: true,
      covered: true,
      cost: null,
      notes: "Underground parking; strict towing enforcement noted in reviews",
    },
    petPolicy: {
      allowed: true,
      speciesAllowed: "dogs + cats",
      maxPets: 2,
      weightLimit: 50,
      breedRestrictions: "Apply; specifics via PetScreening",
      petAmenities: [],
      notes: "Official: 2 pets max, 50 lb limit, PetScreening required",
    },
    amenities: [
      "fitness center",
      "controlled access / gated entry",
      "elevator",
      "courtyard",
      "underground parking",
      "on-site maintenance + management",
      "package receiving",
      "in-unit W/D",
      "high ceilings",
      "patios/balconies",
    ],
    locationNotes:
      "Near Pioneer Park, Delta Center, Granary District. Walkable to The Gateway, TRAX/FrontRunner.",
    pros: [
      "Low entry pricing on 1BR (~$1,214); 2BR starts $1,499 with promo",
      "8 weeks free 2BR promo",
      "$0 deposit option exists on approved credit",
      "Underground parking + controlled access",
    ],
    cons: [
      "50 lb dog weight cap is firm",
      "Towing enforcement complaints",
      "Homeless/security concerns in parking + stairwells per reviews",
      "Discrepancies reported between advertised and actual unit features",
    ],
    redFlags: [
      "Security concerns in parking + stairwells",
      "Towing enforcement disputes",
    ],
    unknowns: ["Parking monthly cost", "Pet fees via PetScreening"],
    dealbreakers: [],
    niceToHaves: ["$0 deposit option", "Underground parking"],
    followUpQuestions: [
      "What's the actual parking monthly cost?",
      "How does PetScreening pricing typically land for a single dog?",
      "Have security/safety issues in parking improved?",
    ],
    comments: [],
    sources: [
      {
        id: "a5-1",
        url: "https://www.altitudeonfifthapartments.com/pet-policy",
        type: "official",
        dateAccessed: today,
        notes: "Pet policy: 2 max, 50 lb, PetScreening required",
        confidence: "high",
      },
      {
        id: "a5-2",
        url: "https://www.rentcafe.com/apartments/ut/salt-lake-city/altitude-on-fifth-0/default.aspx",
        type: "listing",
        dateAccessed: today,
        notes: "Per-unit pricing, $400 deposit, $35 app",
        confidence: "high",
      },
      {
        id: "a5-3",
        url: "https://www.apartmentratings.com/ut/salt-lake-city/altitude-on-fifth_801533066384101/",
        type: "review",
        dateAccessed: today,
        notes: "49 historical reviews",
        confidence: "medium",
      },
    ],
    scores: {
      value: 8,
      location: 7,
      unitQuality: 7,
      amenities: 6,
      commute: 8,
      fees: 7,
      risk: 5,
      personalPreference: 6,
    },
    tour: {
      scheduled: false,
      date: "",
      completed: false,
      notes: "",
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      applicationDeadline: "",
      requiredDocuments: "",
    },
    reviewSummary: {
      rating: 4.5,
      reviewCount: 21,
      source: "RentCafe",
      commonPraise: [
        "responsive management",
        "maintenance responsiveness",
        "downtown location",
        "underground parking",
      ],
      commonComplaints: [
        "parking towing concerns",
        "security in parking/stairwells",
        "ad-vs-actual unit discrepancies",
        "gate reliability",
      ],
    },
    tags: ["value", "downtown", "weight-limit-50"],
    confidence: "medium",
    missingData: [
      "parking cost",
      "pet deposit + fee + rent (PetScreening-mediated)",
      "admin fee",
    ],
  }),

  make({
    rank: 8,
    status: "Interested",
    name: "Meridian",
    address: "30 N Orange St, Salt Lake City, UT 84116",
    neighborhood: "Poplar Grove (North Temple TRAX corridor)",
    website: "https://www.meridianslc.com/",
    rent: 1535,
    rentRangeLow: 1535,
    rentRangeHigh: 1600,
    unitType: "2BR/2BA",
    squareFeet: 976,
    availability:
      "Limited 2BR inventory; 2BR pricing often 'upon request'. Active 1BR special favors 1BR availability.",
    leaseTerms:
      "Standard; current special: 8 weeks free base rent on 1-bedroom homes (move in by May 31).",
    fees: {
      application: 45,
      admin: null,
      deposit: null,
      parking: null,
      petDeposit: 250,
      petFee: 250,
      petRent: 45,
      other: [],
    },
    utilities: {
      included: [],
      tenantPaid: ["electricity", "water", "gas", "internet"],
      estimatedMonthly: 140,
    },
    parking: {
      available: true,
      covered: true,
      cost: null,
      notes: "Covered + off-street options; EV charging available",
    },
    petPolicy: {
      allowed: true,
      speciesAllowed: "dogs + cats",
      maxPets: 2,
      weightLimit: null,
      breedRestrictions: "Not specified; call leasing",
      petAmenities: ["dog wash"],
      notes: "$250 deposit + $250 fee + $45/mo per RentCafe",
    },
    amenities: [
      "24-hour fitness studio",
      "pool",
      "spa",
      "clubhouse with fireplace",
      "dog wash",
      "bike storage",
      "EV charging",
      "parcel lockers",
      "valet trash",
      "front-load W/D",
      "quartz countertops",
      "walk-in closets",
      "hardwood flooring",
      "patio/balcony",
    ],
    locationNotes:
      "Across from UTA TRAX on North Temple; ~2 mi from downtown. Walk 50 / Transit 55. Near 9 Line Trail + Poplar Grove Park.",
    pros: [
      "Strong 2BR value ($1,535–$1,600 base)",
      "Dog wash + EV charging",
      "Direct TRAX access on North Temple",
      "Confirmed pet fee structure",
    ],
    cons: [
      "Walk Score 50 — area is car-dependent",
      "2BR availability is thin (1BR-heavy promo)",
      "Smoking smell complaints despite no-smoke policy",
    ],
    redFlags: ["Smoking smell in common areas per reviews"],
    unknowns: ["Security deposit", "Parking monthly cost", "Pet weight limit"],
    dealbreakers: [],
    niceToHaves: ["EV charging", "Direct TRAX"],
    followUpQuestions: [
      "Any 2BR availability for target move-in date?",
      "Has the smoking smell issue been addressed?",
      "Parking cost?",
    ],
    comments: [],
    sources: [
      {
        id: "md-1",
        url: "https://www.rentcafe.com/apartments/ut/salt-lake-city/meridian1/default.aspx",
        type: "listing",
        dateAccessed: today,
        notes: "Pet $250/$250/$45, $45 app, 4.0/5",
        confidence: "high",
      },
      {
        id: "md-2",
        url: "https://www.apartments.com/meridian-salt-lake-city-ut/xy47cmn/",
        type: "listing",
        dateAccessed: today,
        notes: "Pricing $1,099–$1,600, 8 weeks free 1BR promo",
        confidence: "high",
      },
    ],
    scores: {
      value: 9,
      location: 5,
      unitQuality: 7,
      amenities: 7,
      commute: 6,
      fees: 8,
      risk: 5,
      personalPreference: 6,
    },
    tour: {
      scheduled: false,
      date: "",
      completed: false,
      notes: "",
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      applicationDeadline: "",
      requiredDocuments: "",
    },
    reviewSummary: {
      rating: 4.0,
      reviewCount: 9,
      source: "RentCafe",
      commonPraise: [
        "cleanliness",
        "responsive staff",
        "amenities (gym/pool/clubhouse)",
        "city + mountain views",
        "TRAX access",
      ],
      commonComplaints: [
        "smoking smell despite no-smoke policy",
        "spa closures",
        "gym maintenance",
        "package handling",
        "pet waste in common areas",
      ],
    },
    tags: ["value", "transit", "dog-wash"],
    confidence: "high",
    missingData: [
      "admin fee",
      "security deposit",
      "parking cost",
      "pet weight/breed restrictions",
    ],
  }),

  make({
    rank: 9,
    status: "Interested",
    name: "Seasons at Library Square",
    address: "310 E 500 S, Salt Lake City, UT 84111",
    neighborhood: "Library Square / Central City",
    website: "https://librarysquare.seasonsforrent.com/",
    rent: 2000,
    rentRangeLow: 2000,
    rentRangeHigh: 3364,
    unitType: "2BR/2BA",
    squareFeet: 800,
    availability:
      "6 units listed; 2BR Shakespeare + similar layouts available.",
    leaseTerms:
      "Specials: Move in Now → 3 weeks free; Spring Savings $299 deposit + waived $300 lease initiation.",
    fees: {
      application: null,
      admin: null,
      deposit: 500,
      parking: 70,
      petDeposit: 300,
      petFee: 300,
      petRent: 45,
      other: [
        "$40/mo mandatory trash valet",
        "$300 lease initiation (currently waived)",
      ],
    },
    utilities: {
      included: [],
      tenantPaid: [
        "electricity",
        "water",
        "gas",
        "internet",
        "trash valet ($40/mo)",
      ],
      estimatedMonthly: 175,
    },
    parking: {
      available: true,
      covered: true,
      cost: 70,
      notes: "Secure underground garage; charged per vehicle",
    },
    petPolicy: {
      allowed: true,
      speciesAllowed: "dogs (≤50 lb) + cats (≤25 lb)",
      maxPets: 2,
      weightLimit: 50,
      breedRestrictions: "Apply; not published",
      petAmenities: [],
      notes:
        "Apartments.com shows tiered pet rent: $45 (<40 lb) / $70 (>40 lb). Official site shows $50/mo.",
    },
    amenities: [
      "fitness center",
      "hot tub / spa",
      "business center",
      "clubhouse",
      "game room",
      "stadium theater (surround sound)",
      "outdoor fireplace",
      "outdoor BBQ",
      "community courtyard + sun deck",
      "secure underground parking",
      "electronic keys",
      "high-speed fiber internet",
      "in-unit W/D",
      "9-ft ceilings",
      "granite countertops",
      "hardwood cabinetry",
      "gas stove",
    ],
    locationNotes:
      "Directly across from SLC Main Library + Library Square. Walking distance to all three TRAX lines; restaurants + shopping.",
    pros: [
      "Across from Library Square + all 3 TRAX lines",
      "Stadium theater + game room",
      "Spring Savings: $299 deposit + waived $300 lease initiation",
      "Granite + gas stove (less common at this price)",
    ],
    cons: [
      "$40/mo trash valet is mandatory on top of base rent",
      "50 lb dog weight cap",
      "Thin wall / sound insulation complaints",
      "Property manager turnover noted in reviews",
    ],
    redFlags: ["Tiered pet rent confusion (official $50 vs listing $45/$70)"],
    unknowns: ["Application fee", "Admin fee", "Breed restriction list"],
    dealbreakers: [],
    niceToHaves: ["Stadium theater", "Direct TRAX access"],
    followUpQuestions: [
      "Confirm exact pet rent for a 30 lb dog ($45 or $50 or $70?)",
      "Has the property manager turnover stabilized?",
      "What's the application fee?",
      "Sound insulation between units?",
    ],
    comments: [],
    sources: [
      {
        id: "sl-1",
        url: "https://librarysquare.seasonsforrent.com/pets/",
        type: "official",
        dateAccessed: today,
        notes: "Pet deposit $300, fee $300, rent $50/mo",
        confidence: "high",
      },
      {
        id: "sl-2",
        url: "https://www.apartments.com/seasons-at-library-square-salt-lake-city-ut/xfc1sfn/",
        type: "listing",
        dateAccessed: today,
        notes:
          "$70/mo parking, dog 50 lb / cat 25 lb, tiered pet rent, 3 weeks free promo",
        confidence: "high",
      },
      {
        id: "sl-3",
        url: "https://www.apartmentratings.com/ut/salt-lake-city/seasons-at-library-square_9199332346275159324/",
        type: "review",
        dateAccessed: today,
        notes: "27 reviews",
        confidence: "high",
      },
    ],
    scores: {
      value: 7,
      location: 9,
      unitQuality: 7,
      amenities: 7,
      commute: 9,
      fees: 6,
      risk: 5,
      personalPreference: 6,
    },
    tour: {
      scheduled: false,
      date: "",
      completed: false,
      notes: "",
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      applicationDeadline: "",
      requiredDocuments: "",
    },
    reviewSummary: {
      rating: null,
      reviewCount: 27,
      source: "ApartmentRatings.com",
      commonPraise: [
        "attentive responsive management",
        "prime downtown location near library/transit",
        "well-maintained amenities",
        "secure building",
        "spacious rooms + natural light",
      ],
      commonComplaints: [
        "thin walls / poor sound insulation",
        "property manager turnover",
        "pricier rent for location",
      ],
    },
    tags: ["central", "transit", "weight-limit-50"],
    confidence: "high",
    missingData: [
      "application + admin fees",
      "breed restriction list",
      "tiered pet rent reconciliation",
    ],
  }),

  make({
    rank: 10,
    status: "Needs research",
    name: "Post District Residences",
    address: "570 S 300 West, Suite 101, Salt Lake City, UT 84101",
    neighborhood: "Granary District / Post District",
    website: "https://www.liveatpost.com/",
    rent: 2069,
    rentRangeLow: 2069,
    rentRangeHigh: 4134,
    unitType: "2BR/2BA",
    squareFeet: 764,
    availability:
      "111–126 units across 4 buildings (The Register, 801 Flats, Post House North + South); 2BR 764–1,907 sqft $2,069–$4,134.",
    leaseTerms:
      "Flexible by unit. Special: up to 12 weeks FREE / 'up to $7,500 off rent' on select.",
    fees: {
      application: 50,
      admin: null,
      deposit: null,
      parking: null,
      petDeposit: null,
      petFee: null,
      petRent: null,
      other: [
        "PetScreening required (cost not specified)",
        "Pet fees mediated by PetScreening",
      ],
    },
    utilities: {
      included: [],
      tenantPaid: ["all utilities resident-paid"],
      estimatedMonthly: 175,
    },
    parking: {
      available: true,
      covered: true,
      cost: null,
      notes: "Garage parking + EV charging stations",
    },
    petPolicy: {
      allowed: true,
      speciesAllowed: "dogs + cats",
      maxPets: 2,
      weightLimit: 50,
      breedRestrictions: "Standard via PetScreening; not publicly listed",
      petAmenities: ["dog wash station"],
      notes: "50 lb weight cap per pet; PetScreening required",
    },
    amenities: [
      "7,000+ sqft fitness center",
      "indoor + outdoor pools (year-round)",
      "spa",
      "movie theater",
      "golf simulator",
      "creative studio",
      "rooftop lounges",
      "business center",
      "marketplace",
      "grill area",
      "garage parking",
      "EV charging",
      "bike storage",
      "dog wash",
      "in-unit W/D",
      "smart lock access",
    ],
    locationNotes:
      "Granary/Post District south downtown; pedestrian-friendly; mixed-use neighborhood with breweries + restaurants. 4-building campus.",
    pros: [
      "Best overall amenity package in this list (theater, golf sim, year-round pools)",
      "12 weeks free / up to $7,500 off promo",
      "Multiple buildings / many floor plans available",
      "Dog wash + EV charging + bike storage",
    ],
    cons: [
      "50 lb dog weight cap",
      "PetScreening adds friction + unclear pet costs",
      "Bike theft from secure bike lockers reported in reviews",
      "Hidden fees + build-quality complaints surface on Reddit",
    ],
    redFlags: [
      "Bike theft from 'secure' lockers per reviews",
      "Reddit complaints about hidden fees + management responsiveness",
    ],
    unknowns: [
      "Exact pet costs (PetScreening-mediated)",
      "Security deposit",
      "Admin fee",
      "Parking monthly cost",
    ],
    dealbreakers: [],
    niceToHaves: ["Movie theater", "Golf simulator"],
    followUpQuestions: [
      "Full disclosure of monthly fees beyond base rent?",
      "Typical PetScreening pet cost for a single dog?",
      "Has bike theft been addressed since reviews?",
      "Build-quality status of newer buildings?",
    ],
    comments: [],
    sources: [
      {
        id: "pd-1",
        url: "https://www.liveatpost.com/",
        type: "official",
        dateAccessed: today,
        notes: "4-building layout, 12-weeks-free promo",
        confidence: "high",
      },
      {
        id: "pd-2",
        url: "https://www.rentcafe.com/apartments/ut/salt-lake-city/post-house/default.aspx",
        type: "listing",
        dateAccessed: today,
        notes: "Rent ranges, sqft, $50 app, 50 lb max pet",
        confidence: "high",
      },
      {
        id: "pd-3",
        url: "https://www.yelp.com/biz/post-district-residences-salt-lake-city-2",
        type: "review",
        dateAccessed: today,
        notes: "15 reviews",
        confidence: "medium",
      },
    ],
    scores: {
      value: 6,
      location: 8,
      unitQuality: 8,
      amenities: 10,
      commute: 8,
      fees: 5,
      risk: 4,
      personalPreference: 7,
    },
    tour: {
      scheduled: false,
      date: "",
      completed: false,
      notes: "",
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      applicationDeadline: "",
      requiredDocuments: "",
    },
    reviewSummary: {
      rating: null,
      reviewCount: 15,
      source: "Yelp",
      commonPraise: [
        "responsive friendly staff",
        "amazing amenities",
        "appealing design",
        "community atmosphere",
        "new construction",
      ],
      commonComplaints: [
        "bike theft from secure lockers",
        "pet restriction details unclear",
        "PetScreening complexity",
      ],
    },
    tags: ["amenities", "luxury", "weight-limit-50", "campus"],
    confidence: "medium",
    missingData: [
      "exact pet deposit/fee/rent",
      "security deposit",
      "admin fee",
      "parking cost",
    ],
  }),
];
